// <auto-generated />
namespace EventAttendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class whatsapp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatsapp));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240016246_whatsapp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
